Improve score labels
huichops/simon pull request #25
Opened 2017-06-21 03:57 UTC by Alex-TH

Vean que bonis!!!!!!

<img width="587" alt="screen shot 2017-06-20 at 10 56 16 pm" src="https://user-images.githubusercontent.com/3271947/27366435-b65a99e2-560b-11e7-946b-f69bbb4db366.png">

2017-06-21 18:11 UTC, huichops requested changes
Haz paro, que jale el High Score jaja

2017-06-21 18:16 UTC, beeetooo commented
Y hazle pruebas ^

2017-06-21 18:50 UTC, Alex-TH commented
solo era pr de diseño :(

2017-06-21 21:47 UTC, huichops commented
entonces alv, porque sino tiene una intención es mal diseño jaja
Comprendo que si lo va a tener y así, pero ponerse serios en estos detallitos se adapta más al mundo real y nos hace mejores ingenieros <3

2017-06-21 23:52 UTC, Alex-TH commented
lo 100to

2017-06-22 13:56 UTC, aromeronavia commented on scripts/game-state.js
> +    this.hiScore = this.score > this.hiScore ? this.score : this.hiScore;
```js
this.hiScore = Math.max(this.score, this.hiScore);
```

2017-06-22 13:56 UTC, aromeronavia commented on scripts/game-state.js
> +  resetGame() {
Creo que aquí podrías guardar el hiScore en local storage :+1:

2017-06-22 22:26 UTC, Alex-TH commented on scripts/game-state.js
> +    this.hiScore = this.score > this.hiScore ? this.score : this.hiScore;
que jipster ❤️

2017-06-22 22:50 UTC, Alex-TH commented
listo amiguitos ❤️

2017-06-23 11:41 UTC, huichops commented on scripts/game-state.js
> +  resetGame() {
tiiiii

2017-06-23 21:18 UTC, servandocty commented on test/game-state.test.js
> +const inscreaseScore = (state, times) => {
increaseScore :P

2017-06-23 22:01 UTC, Alex-TH commented on test/game-state.test.js
> +const inscreaseScore = (state, times) => {
😱

2017-06-26 16:23 UTC, huichops commented on .babelrc
> +  "presets": ["es2015"]
si o que

2017-06-26 16:23 UTC, aromeronavia requested changes

2017-06-26 16:23 UTC, aromeronavia commented on scripts/game.js
>    onColorClick(event) {
Esta función ya está muy larga :( pártela mae

2017-06-26 16:23 UTC, aromeronavia commented on test/game-state.test.js
> +  for(let i = 0; i < times; i += 1) state.increaseScore();
Ocupamos el linter que nos diga que for y ( van espaciados

2017-06-26 16:25 UTC, huichops requested changes
test statements pe

2017-06-26 16:25 UTC, huichops commented on test/game-state.test.js
> +test('hiScore should be preserved', () => {
esas dos descripciones son iguales pe

2017-06-26 16:25 UTC, huichops commented on test/game-state.test.js
> +test('Reset score should set hiScore', () => {
reset game

2017-06-26 22:05 UTC, Alex-TH commented on .babelrc
> +  "presets": ["es2015"]
jajaja

2017-06-26 22:09 UTC, Alex-TH commented on test/game-state.test.js
> +test('hiScore should be preserved', () => {
Listo

2017-06-26 22:53 UTC, Alex-TH commented on scripts/game.js
>    onColorClick(event) {
sorry, hay un buen de codigo repetido, la estoy arreglando

2017-06-26 22:56 UTC, Alex-TH commented on scripts/game.js
>    onColorClick(event) {
❤️

2017-06-26 23:17 UTC, Alex-TH commented on test/game-state.test.js
> +  for(let i = 0; i < times; i += 1) state.increaseScore();
👍

2017-06-27 18:11 UTC, huichops commented on .eslintrc
> +  }
jálate el de airbnb, está verga

2017-06-27 18:12 UTC, huichops approved these changes
dale <3

2017-06-27 18:31 UTC, Alex-TH commented on .eslintrc
> +  }
es que incluye muchas reglas de riact, pero si gustan lo metemos

2017-06-27 19:18 UTC, beeetooo commented on .eslintrc
> +  }
Nel, esas están bien

2017-06-27 19:20 UTC, aromeronavia reviewed
Estoy pensando a creer que GameState tiene dos responsabilidades, el score y el state.
Deberíamos separar las responsabilidades? Porque chequen los tests cómo están acoplados a hacer cambios del state para empezar a meter scores y así, cuando el score ni siquiera tendría que saber de game states, es sólo score.

Pero bueno, supongo que podríamos hacer improvement de eso después, o no.

2017-06-27 19:54 UTC, Alex-TH commented
Como lo veo es que los scores son parte de state del juego, incluso la secuencia tambien podria ser parte del state, de esa forma todo podria cambiar en GameState y lo demas simplemente consumirlo, es mi idea pues, no se como se les haga :D

2017-07-04 18:16 UTC, aromeronavia approved these changes

2017-07-05 17:22 UTC, merged